### ISSUE TITLE
CropViewController fails in Xcode due to Imcompatible Swift Versions

### ISSUE THREAD

**Issue by BrogrammerGV** [NeutrinosPlatform/cordova-plugin-document-scanner#13]
For reference:
Using ionic@latest, xcode@latest, cordova@latest.

When building my app from Xcode to live device (build works fine on simulator) I get a 'Build Failed' due to the CropViewController and "Incompatible versions of Swift". Interestingly enough, simply  removing the embedded binaries for 'CropViewController' within Xcode i'm able to build and use the plugin just fine in the app.

Here is an excerpt from the Error Log: 
![screen shot 2018-05-24 at 2 58 02 pm](https://user-images.githubusercontent.com/14019865/40510762-48ed3268-5f63-11e8-915d-89c2f49db355.png)

**The highlighted binaries that cause build to fail**
![screen shot 2018-05-24 at 2 51 58 pm](https://user-images.githubusercontent.com/14019865/40510433-53cfdc68-5f62-11e8-8d4d-0883c120b211.png)

**Comment by ChrisTomAlx** [comment]
Thank you for bringing this issue up. I will look into it and see what can be done. Meanwhile I am glad you got it to work for yourself. If a workaround can't be found for this issue, will add your solution to the documentation for future users to access easily.
