### ISSUE TITLE
iOS: Very hard to understand the UI and buttons 

### ISSUE THREAD

**Issue by dylanvdmerwe** [NeutrinosPlatform/cordova-plugin-document-scanner#15]
Where can we find documentation as to what the various buttons do on iOS. They are not very intuitive and users are very confused (and so I am) about what they all do.

**Comment by ChrisTomAlx** [comment]
![whatsapp image 2018-05-31 at 2 10 14 pm 1](https://user-images.githubusercontent.com/34361280/40773734-69deea60-64e1-11e8-9cc3-858a5b40e0b2.jpeg)
![whatsapp image 2018-05-31 at 2 10 15 pm](https://user-images.githubusercontent.com/34361280/40773738-6b881cb0-64e1-11e8-952c-1a34ee175ca8.jpeg)

I hope this clears up some of the confusion. The accuracy/performance button does not make a big difference as far as I could tell. Work on both android and ios libraries to optimize and improve overall performance will be our main focus once work on the plugin starts up again.

Thank you for bringing these issues to our attention. Unfortunately I can't help you too much with enhancements in the short term, but all of these will be addressed at one point.

**Comment by nithilch** [comment]
Can we customize to have the manual scan as default?

**Comment by mLuby** [comment]
I've been looking to customize this too (and the other buttons) but I can't find where any of this is defined. Searches through the repo for "Manual" and "Auto" turn up nothing even though that text must be somewhere. If you can give me any hints @ChrisTomAlx I might be able to PR my changes to make this more customizable for other users too.

**Comment by ChrisTomAlx** [comment]
> #### TL:DR
> Make changes in the [library](https://github.com/charlymr/IRLDocumentScanner), Build the library using carthage, add the framework build files to the plugin within the ios folder as seen in this repo. If there are changes that affect user input, i.e. user customization, then change the scan.js file to accept these inputs either as an object (better but requires android changes, currently android accepts array) or as an array.

**Please** read the long version below, it has more info I haven't mentioned above.

 - The document scanner plugin uses IRLDocumentScanner library found [here](https://github.com/charlymr/IRLDocumentScanner).

 - Some customization can be achieved directly by changing the relevant lines in the `scan.m` file as shown below. It even allows changing the overlay color when auto scan occurs (which is not mentioned here). More customisations (does not include auto - manual scan) that are readily allowed by the library and hence does not require rebuilding the library, can be found [here](https://github.com/charlymr/IRLDocumentScanner/blob/master/Source/Public/IRLScannerViewController.h).

   ```
   // Creates scanner with default scanner view type and performance type
   IRLScannerViewController *scanner = [IRLScannerViewController 
   cameraViewWithDefaultType:IRLScannerViewTypeNormal 
   defaultDetectorType:IRLScannerDetectorTypePerformance withDelegate:self];

   scanner.showControls = YES;
   scanner.showAutoFocusWhiteRectangle = YES;
   [IRLScannerViewController attemptRotationToDeviceOrientation];
   ```

 - Making these changes, also means we will have to find similar changes in the android [library](https://github.com/jhansireddy/AndroidScannerDemo) (Or choose not to do anything in android when these customization are requested). Either way the `scan.js` file which currently looks like below will have to be changed:

```
module.exports = {
    scanDoc: function (sourceType, successCallback, errorCallback) {
        cordova.exec(successCallback, errorCallback, "Scan", "scanDoc", [sourceType]);
    }
};
```
 - This will need to be changed to either support taking an object (Better code, but slightly harder to implement) as the input or take more inputs in the current array, as shown below
1) **object**

```
// eg optionObject
// {
//   sourceType : 0; 
//   detectorView: IRLScannerDetectorTypePerformance; // type enum in obj C
//   scanView: IRLScannerViewTypeNormal; // type enum in obj C
//   overlayColor: #FFFFFF; // type color in obj C
// }
module.exports = {
    scanDoc: function (optionObject, successCallback, errorCallback) {
        cordova.exec(successCallback, errorCallback, "Scan", "scanDoc", optionObject);
    }
};
```

2) **array**

```
module.exports = {
    scanDoc: function (sourceType, detectorView, scanView, successCallback, errorCallback) {
        cordova.exec(successCallback, errorCallback, "Scan", "scanDoc", [sourceType, detectorView, scanView]);
    }
};
```

If choosing the array way then changes to android aren't required, but don't change array index positions, for eg do not switch sourceType to the end of the array, this will cause issues.

- Any changes you want on the UI or customization changes that can't directly be called from outside the library (like setting manual scan as default option) will have to be done within the library which will then have to be built with carthage to create the framework files that we use in this plugin, seen within the ios folder. You can replace the current framework files with the new ones and raise a pull request.

> Note :- The passing as object into `scan.js` for scalability and the addition of already available customisations as user inputs are enhancements that will soon (can't promise a date as of yet) be addressed by us.

**Comment by tiplonski** [comment]
Hello Chris,

I didn't see an option as to where you can default the plugin for IOS to be manual instead of automatic.  Can you direct me to the setting that would achieve this?

Thanks,
Tim
