### ISSUE TITLE
How to add rotate options

### ISSUE THREAD

**Issue by SyedAliHassanShahBukhari** [NeutrinosPlatform/cordova-plugin-document-scanner#16]
Please give documentation related to option customization like switch to portrait or landscape, after cropping rotate option. 
Every time I took picture in portrait mode it rotate the image to landscape mode in cropping mode and save it as landscape mode. Please reply ASAP.

**Comment by ChrisTomAlx** [comment]
Will be adding two buttons in scan library to rotate image soon. Before the end of next week if time permits. Will let you know as soon as its done.

**Comment by SyedAliHassanShahBukhari** [comment]
@ChrisTomAlx Thanks, I am waiting for the update.

**Comment by ChrisTomAlx** [comment]
@SyedAliHassanShahBukhari This issue has now been fixed. Tested successfully on my end. Please do let me know if you run into trouble.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by SyedAliHassanShahBukhari** [comment]
@ChrisTomAlx  Thanks it's working fine.
