### ISSUE TITLE
Low quality on selecting a picture

### ISSUE THREAD

**Issue by uzumakinaruto123** [NeutrinosPlatform/cordova-plugin-document-scanner#23]
On Android Device,

Image selected from Gallery/File Source is of very low quality. 

Same image when opened via any File manager has very good quality. I suppose plugin is doing some compression on the image.

**Comment by alexbogo** [comment]
Hi, which platform you are using, PhoneGap, Ionic... ?

**Comment by uzumakinaruto123** [comment]
Following are the platform details:

```
ionic info

cli packages: (C:\Users\sd\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.0
    npm               : 5.2.0
    OS                : Windows 10

```

**Comment by ChrisTomAlx** [comment]
@uzumakinaruto123 Fixed! Try now. Although low end devices will have some memory trouble now. Tested in mine and it is working. Gallery shows high quality images. Closing this issue for now. Let me know if this helped. :) 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by uzumakinaruto123** [comment]
@ChrisTomAlx By re-request do you mean removing and reinstalling plugin? Actually I am confused as I don't see any commits in the repo?

**Comment by ChrisTomAlx** [comment]
@uzumakinaruto123 the commits are in the [scanlibrary](https://github.com/NeutrinosPlatform/scanlibrary) used for the plugin. Removing and re-adding will most likely do it. But I would suggest starting from a blank project if you just want to test this plugin.
