### ISSUE TITLE
Plugin crashes after update

### ISSUE THREAD

**Issue by waqasmq** [NeutrinosPlatform/cordova-plugin-document-scanner#24]
Hi chris,
I built my ionic app  today after some other changes ( not related to this plugin).. and i saw it updated the cordova scan plugin.. and since then this plugin starts to crash. it does not open camera or gallery options :( ..  
and in the phone log i can see this exception

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.ionic.starter-eC91gWckgNN3MK_UB9WYeA==/base.apk"],nativeLibraryDirectories=[/data/app/io.ionic.starter-eC91gWckgNN3MK_UB9WYeA==/lib/arm64, /system/lib64, /system/vendor/lib64]]] couldn't find "libopencv_java3.so"`

I was able to solve this by following the solution in this thread [https://stackoverflow.com/questions/33030900/android-unsatisfiedlinkerror-with-tesseract-and-opencv](url)

any ideas about a proper fix?

**Comment by waqasmq** [comment]
Hey @ChrisTomAlx ,
I have tested now without the workaround and its works fine. Thanks for the help mate 👍 

Regards,
Waqas

**Comment by ChrisTomAlx** [comment]
@waqasmq 

That is great news. Will let the people on the other issue know this has been fixed as well.

Cheers and thanks a ton for your help :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by openopen114** [comment]
i got the same crash issue on Android before...
but i "git clone" my ionic project
and then "npm i", "ionic cordova platform add android"

right now it works perfectly on the phone !!
sooo thank you for fix this issue

**Comment by ChrisTomAlx** [comment]
@openopen114 

I am glad that it worked for you ;)

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
