### ISSUE TITLE
Phonegap build

### ISSUE THREAD

**Issue by menjada** [NeutrinosPlatform/cordova-plugin-document-scanner#25]
Can not make this plugin to work. Is there anything else i need to do if i use Phonegapbuild.

scan.scanDoc(0, onSuccessScan, onFailScan); 
Does nothing? Reqular accessing the camera works fine?

**Comment by ChrisTomAlx** [comment]
Hey @menjada 

I hope you have already read the documentation and other issues before posting this. Issue #22 is regarding exactly this and it has been mentioned in the documentation under issues and fixes. If you did try everything and it still isn't working. Please tell me what you tried and also please let me know what your `cordova`, `cordova-android` and `cordova-ios` versions are. You can get this info by using `cordova platform` in the CLI. I would also like any other technical detail you can provide. Like mobile device platform[Android / Ios], Platform version etc.

Also try `console.log(scan)` and let me know what output you are getting.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
Hey @menjada 

Yes according to that issue you do need CLI. Although I haven't personally tried it, I don't think phonegap build desktop tool alone will work. The issue poster of that issue had this same problem and he explains how he solved it by installing a few other tools like Android Studio and Cordova CLI.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
@menjada I am closing this issue for now. Let me know if you need any more help with setting up the CLI to get this to work.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
