### ISSUE TITLE
Not working with cordova 8

### ISSUE THREAD

**Issue by Karanveer-logiciel** [NeutrinosPlatform/cordova-plugin-document-scanner#29]
Hello @ChrisTomAlx - It's not working for me. I am using cordova 8.0.0

**Comment by ChrisTomAlx** [comment]
Hey @Karanveer-logiciel 
Oh! Just double checked. I am using cordova 8.0.0 as well and I don't seem to have any problems. What about the cordova android version ? iOS is working alright for you I am assuming. Could you paste you entire js file code here?

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by Karanveer-logiciel** [comment]
@ChrisTomAlx - It's working now sorry :- (

**Comment by ChrisTomAlx** [comment]
@Karanveer-logiciel 

Oh awesome! If you made changes to get it to work, it would be helpful if you posted them here. Anyhow closing the issue for now. Have a nice day!

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
