### ISSUE TITLE
Android 8

### ISSUE THREAD

**Issue by FaberDL89** [NeutrinosPlatform/cordova-plugin-document-scanner#30]
Hi i have a problem for to release app with target api 26

**Comment by ChrisTomAlx** [comment]
Hey @FaberDL89 ,

This issue has been clearly documented in the readme. Please consider going through the documentation before posting issues. Duplicate of issue #17.

Here is the hotfix solution you can use :-
Add <preference name="android-targetSdkVersion" value="25" /> to your config.xml under platform android.

Closing this issue. If you need help please continue in issue #17

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by FaberDL89** [comment]
i can't becouse if i release on play store it want a app with android-targetSdkVersion 26

**Comment by FaberDL89** [comment]
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

**Comment by ChrisTomAlx** [comment]
@FaberDL89 
Oh. Will see what can be done about a permanent fix for this. Will let you know once I make some progress.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by muhammadsamir11** [comment]
Hi @ChrisTomAlx any update about this issue
Thanks a lot

**Comment by ChrisTomAlx** [comment]
Hey @muhammadsamir11 

I haven't yet tested on a real device but my colleague ran tests on an Android 8.0 Emulator successfully. Although I don't think that is enough. I will run tests on a real device as soon as I get my hands on one.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
Fixed and tested on Android 8+( Including 9 )

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
