### ISSUE TITLE
App crash in android 7.0

### ISSUE THREAD

**Issue by Karanveer-logiciel** [NeutrinosPlatform/cordova-plugin-document-scanner#32]
@ChrisTomAlx - I am facing problem to use this plugin i have android 7.0 (Samsung s2 tab). 
 
when i call `scan.scanDoc` my app crashing with error showing below.

![image](https://user-images.githubusercontent.com/22929265/45362092-85b86480-b5f1-11e8-8539-5e997c872552.png)

Here you can see in yellow lines 'couldn't find libScanner.so`

But i extract my .apk file where it's not present but in similar folders this file is already present such as armeabi, armeabi-v7a, mips, x86 except arm64-v8a, x86_64  for more clarification you kindly look at images.

![sc](https://user-images.githubusercontent.com/22929265/45362613-e98f5d00-b5f2-11e8-94b4-ddc94250b0e4.PNG)

These are the folders of extracted .apk

**Comment by ChrisTomAlx** [comment]
Hey @Karanveer-logiciel 

This looks similar to issue #8 . Please see if those solutions work out.

It is possible a 64 bit build library was loaded first and hence android is looking for a 64 bit library for the scan library as well. The solution mentioned above should work for you.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by Karanveer-logiciel** [comment]
@ChrisTomAlx - Ok i will try this solutions shortly...

**Comment by ChrisTomAlx** [comment]
Closing this issue for now. We can reopen it, if you are still having problems. 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
