### ISSUE TITLE
Feature Request:  PDF Generation

### ISSUE THREAD

**Issue by humblecoder** [NeutrinosPlatform/cordova-plugin-document-scanner#33]
It would be nice if direct PDF generation were an option.  As it stands, I must take the data and convert it manually.  That said, I definitely appreciate discovering this plugin in light of all the overpriced ones out there.

**Comment by ChrisTomAlx** [comment]
Hey @humblecoder it is you again! Thank you for the wonderful compliment.

I am sorry to be the bringer of sad news but the edge detection and perspective correction libraries themselves cause this plugin to be huge. Adding a PDF conversion library, especially if you are not going to use it, would in my opinion be more harmful than helpful. That being said, it would be a great idea to have a seperate plugin that takes jpegs, pngs, docs etc. and convert them into a PDF for you. If it doesn't already exist, I would say we just might make the time to make it ourselves.

Have a nice day and thank you for raising these issues :)  

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
