### ISSUE TITLE
Bypass filter screen

### ISSUE THREAD

**Issue by RPocas** [NeutrinosPlatform/cordova-plugin-document-scanner#36]
First of all, congratulations for the excellent work!

I wonder if it is possible to skip the filters screen, and save the image directly?

Thank you very much

**Comment by ChrisTomAlx** [comment]
Hey @RPocas 

Unfortunately at the present moment this is not possible. Also I would say the filter screen is important to correct the orientation of the image scanned. This could be an enhancement for the future but in the short term, I can't provide you with any solutions other than changing the scan library's native code to completely skip over the filter screen. Wish I could have been of more help.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by project30003** [comment]
Hi @ChrisTomAlx,

I wanted to change the scan library's native code to completely skip over the filter screen but i have no idea how to fork the code and to edit them. I refer to the #60 to do them but i have no experience in doing fork and edit the code. Is there any way you can guide me?

Thanks,
Sam
