### ISSUE TITLE
Update to support play store (target android 26+)

### ISSUE THREAD

**Issue by Thomasbehan** [NeutrinosPlatform/cordova-plugin-document-scanner#37]
since the 1st of November the play store will not allow new or updated apps target android <=25, apps must now target 26 or above to be allowed on the google play store

Is it possible to update this to support the above?

**Comment by ChrisTomAlx** [comment]
Fixed! Let me know if you have more queries! 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
