### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by dylanvdmerwe** [NeutrinosPlatform/cordova-plugin-document-scanner#4]
I am doing this from scratch to test this plugin. The plugins and platforms folder is empty. 

I then go `cordova platform add android@7.1.0 --save`

and get the following error:
```
Failed to install 'cordova-plugin-document-scanner': Error: ENOENT: no such file or directory, open '/Users/dylan/Desktop/Projects/Antel/platforms/android/AndroidManifest.xml'
```

Am I missing something?

Info:
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v8.11.1
    npm        : 5.8.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3 Build version 9E145
```

**Comment by dylanvdmerwe** [comment]
Is there no way this plugin can work on cordova-android 6?

**Comment by dylanvdmerwe** [comment]
Seems to install fine on a blank ionic project with cordova-android 7.1.

**Comment by ChrisTomAlx** [comment]
Sorry, Right now there is no support for cordova-android 6. But we might work on this in the future. Were you able to solve the Failed-to-install issue?

**Comment by dylanvdmerwe** [comment]
I am going to close this issue for now as I can install the plugin on a blank starter app.
