### ISSUE TITLE
App crash and does not work with multiple sources

### ISSUE THREAD

**Issue by ravi9376** [NeutrinosPlatform/cordova-plugin-document-scanner#41]
hey i m using ionic 4 and angular 6 with cordova 7 and i m using device android 8 version and app crush so  i need help i already tried hot fix but they didn't work  so, help me. and onece i select a image from camera and second time i select from other source then also app is crushes.

**Comment by ChrisTomAlx** [comment]
Hi @ravi9376 

I will need more info to help you solve your issue.
Please send in your Code snippet, Error stack trace, Your project (For more in depth analysis).

If you can send in your project I can test it on my end and see what problem you are running in to.

Also you don't need the hotfix anymore, it should work without it. Another thing is, if the hotfix did not work it means it isn't an issue with the android version.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
Closing since there has been no response. Please reopen if you need to,

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
