### ISSUE TITLE
Android App Build Failed

### ISSUE THREAD

**Issue by ATY77** [NeutrinosPlatform/cordova-plugin-document-scanner#43]
Hi Chris,

Since today the build of the Android App fails with this error.
Can u see what is wrong?

Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Could not resolve com.github.NeutrinosPlatform:scanlibrary:master-SNAPSHOT.
  Required by:
      project :app
   > Could not resolve com.github.NeutrinosPlatform:scanlibrary:master-SNAPSHOT.
      > Unable to load Maven meta-data from https://jitpack.io/com/github/NeutrinosPlatform/scanlibrary/master-SNAPSHOT/maven-metadata.xml.
         > Could not HEAD 'https://jitpack.io/com/github/NeutrinosPlatform/scanlibrary/master-SNAPSHOT/maven-metadata.xml'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by ChrisTomAlx** [comment]
Hey @ATY77 

Sorry I was away for a while and could not get back to you. Are you still facing this issue? 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ATY77** [comment]
Hi Chris,

This issue seems to be solved.

But we still face another issue, please look at issue : 'iOS: Cannot publish app due to unsupported architectures'. This one prevents us from deploying iOS App in Apple Store.

Thanks,

**Comment by ChrisTomAlx** [comment]
Please refer to issue 18 for a temporary fix for this. Will look into solving it permanently in the near future.

Closing for now as the original issue has been fixed. 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by bendspoons** [comment]
@ATY77: Github classsic: Problem solved, but the solution is not posted here. Can you privde your solution to the "ERROR: Failed to resolve: com.github.NeutrinosPlatform:scanlibrary:master-SNAPSHOT" Error? Im facing this currently, nad i have no idea how to fix this (and NO, i read all Issues here and NONE helped...)

Thanks!

**Comment by ChrisTomAlx** [comment]
@bendspoons Please run build again and let me know if you are still getting the error

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by bendspoons** [comment]
Hi, thanks for the reply. OK.

1. Android 7.1.4
2. Cordova 8.1.2

App build / Sync Gradle OK

Run "cordova plugin add cordova-plugin-document-scanner" --> adding Plugin

App build / Sync Gradle fails with

"ERROR: Failed to resolve: com.github.NeutrinosPlatform:scanlibrary:master-SNAPSHOT
Show in Project Structure dialog
Affected Modules: app"

And yes, i added jitpack.io in build.gradle (Module: app)

`allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}`


and added ndk filters

`android {
    defaultConfig {
        applicationId privateHelpers.extractStringFromManifest("package")
        minSdkVersion 21
        targetSdkVersion 28
        if (cdvMinSdkVersion != null) {
            minSdkVersion cdvMinSdkVersion
        }

        ndk {
            abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
        }
}
}`
Thanks!!

**Comment by bendspoons** [comment]
Maybe it has sth to do with a failed build @jitpack?!

If i access https://jitpack.io/com/github/NeutrinosPlatform/scanlibrary/master/snapshot directly, it states "Build failed. See the log at jitpack.io"

**Comment by ChrisTomAlx** [comment]
Yup jitpack build was the issue. I knew that going in, but took some time to fix the issue.

It should be working now. Remove all the older fixes you mentioned in the comment below. It should work correctly without them. Tested it on my end to make sure. Also make sure you remove the older plugin and add the latest one (At the time of writing this, the version is cordova-plugin-document-scanner v2.0.2)

> Hi, thanks for the reply. OK.
> 
> 1. Android 7.1.4
> 2. Cordova 8.1.2
> 
> App build / Sync Gradle OK
> 
> Run "cordova plugin add cordova-plugin-document-scanner" --> adding Plugin
> 
> App build / Sync Gradle fails with
> 
> "ERROR: Failed to resolve: com.github.NeutrinosPlatform:scanlibrary:master-SNAPSHOT
> Show in Project Structure dialog
> Affected Modules: app"
> 
> And yes, i added jitpack.io in build.gradle (Module: app)
> 
> `allprojects {
>     repositories {
>         google()
>         jcenter()
>         maven { url 'https://jitpack.io' }
>     }
> }`
> 
> 
> and added ndk filters
> 
> ```
> android {
>     defaultConfig {
>         applicationId privateHelpers.extractStringFromManifest("package")
>         minSdkVersion 21
>         targetSdkVersion 28
>         if (cdvMinSdkVersion != null) {
>             minSdkVersion cdvMinSdkVersion
>         }
> 
>         ndk {
>             abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
>         }
> }
> }
> ```
> Thanks!!

Cheers and happy coding my friend :) 
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by bendspoons** [comment]
Woha, thanks a lot. 

I was pretty sure the error was its because of Jitpack, the exact same config worked last week.

Thanks a lot for the real quick help! I appreciate it!
