### ISSUE TITLE
scanned image uri return unknown 

### ISSUE THREAD

**Issue by soban5757** [NeutrinosPlatform/cordova-plugin-document-scanner#44]

**Comment by soban5757** [comment]
when i am done with the scan process i got this URI file:///storage/emulated/0/Pictures/1548222903280.jpg
and this URI got nothing

**Comment by ChrisTomAlx** [comment]
Hey @soban5757 

I was away for a while, sorry about the delayed response. So if I understood you correctly, when you console log the URI you get a proper file URI string but the image is empty.

If that is true then I have a few questions.
1. How did you find out the image was empty?
2. Have you tried going into your file explorer and searching for the image? 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
Closing because there hasn't been any response

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
