### ISSUE TITLE
cordova build andorid - Could not resolve all files for configuration ':app:debugCompileClasspath'

### ISSUE THREAD

**Issue by ryancmlee** [NeutrinosPlatform/cordova-plugin-document-scanner#58]
Hi, Could I get some help building this project?
I was able to build and run cordova-plugin-mobile-ocr with no issues.
Thanks!

cordova build android
```
...
> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest UP-TO-DATE
> Task :CordovaLib:processDebugManifest UP-TO-DATE
> Task :app:preDebugBuild
> Task :app:preDebugBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not resolve com.github.NeutrinosPlatform:scanlibrary:2.3.
  Required by:
      project :app
   > Skipped due to earlier error
```

cordova plugin ls
```
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-document-scanner 4.2.0 "Scan"
cordova-plugin-mobile-ocr 3.1.1 "Textocr"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**Comment by ChrisTomAlx** [comment]
Hey @ryancmlee 
I just ran an android build successfully after adding all the same plugins you had added.
Could you remove, then add the platform using `cordova plugin rm android` and `cordova plugin add android`.

This could be and issue with jitpack being down, which is where the android scanlibrary build is hosted.

Also what is your **cordova** version and your **cordova-android** version ?

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ryancmlee** [comment]
Hi Chris,
Thanks so much for the reply and awesome free plugin.
I was able to build after restarting my computer. 
Not sure what the issue was.

Cheers,
Ryan
