### ISSUE TITLE
plugin_not_installed

### ISSUE THREAD

**Issue by sersart** [NeutrinosPlatform/cordova-plugin-document-scanner#66]
Hi, I am getting plugin_not_installed error when starting app on ionic devapp.
"Native: tried calling DocumentScanner.scanDoc, but the DocumentScanner plugin is not installed."
"Install the DocumentScanner plugin: 'ionic cordova plugin add cordova-plugin-document-scanner'"
"plugin_not_installed"

But when starting in ios emulator it works fine

**Comment by ChrisTomAlx** [comment]
Hey @sersart 

Try `cordova plugins` in cli and check if document scanner shows up

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
