### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to draw too large(118591260bytes) bitmap.

### ISSUE THREAD

**Issue by benediktcarda** [NeutrinosPlatform/cordova-plugin-document-scanner#67]
**Describe the bug**
The cordova-plugin-document-scanner crashes with a fatal exception:
"java.lang.RuntimeException: Canvas: trying to draw too large(118591260bytes) bitmap."

It occurs on my Samsung A7 phone (Android 9) and happens, if I choose a too large part of the photo to be the document. If I choose just a small fraction of the photo taken then the bug does not occur.

**To Reproduce**
- call the plugin in your app via: 
> scan.scanDoc(successCallback, errorCallback, options);
- Take a photo
- Select a large part of the photo to be the document
- Hit "next"
--> The app crashes.

**Expected behavior**
The plugin should crop and skew the part of the photo chosen before and show the result on the screen.

**Screenshots**
The crash is silent, not issuing any error message on the devices screen. I got the error message via the adb command of the Android platform-tools.

**Smartphone (please complete the following information):**
 - Device: Samsung A7
 - OS: Android 9
 - Browser: stock browser
 - Cordova Version: 9.0
 - Cordova Platform: Android
 - Cordova Platform Version: 8.0.0

**Comment by ChrisTomAlx** [comment]
Hey @benediktcarda 

Use the quality option to reduce the quality of the captured image. Let me know if this doesn't solve your issue.

![Annotation 2020-01-19 010641](https://user-images.githubusercontent.com/34361280/72669472-f8dcb100-3a57-11ea-9b86-f4e3dbdcfecf.jpg)

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by benediktcarda** [comment]
Hello Chris,
yes, this helps. Still it is an uncatched fatal exception that should be dealt with by issuing some error message. Currently it leads to crashes of the app that uses the plugin.
Still thank you very much for providing this package.
Cheers,
Benedikt.

**Comment by ChrisTomAlx** [comment]
You are right. There wasn't a catch block to catch such unexpected exceptions.
I have added it and published [Ver 4.2.2](https://www.npmjs.com/package/cordova-plugin-document-scanner) of the plugin. 
Closing the issue for now. 
Feel free to reopen it if you think, it doesn't solve your issue.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
