### ISSUE TITLE
There is no abort functionality on Android

### ISSUE THREAD

**Issue by cytostatic** [NeutrinosPlatform/cordova-plugin-document-scanner#68]
When Back-button is pressed on Android neither the succes nor the error callback is fired to cancel the scan.
As a result, it freezes my App.

Is there any solution or is it just a bug?

**Comment by ChrisTomAlx** [comment]
Hey @cytostatic 

Sorry about the delayed response. You were right it was a bug. Fixed and pushed a small update. Get the latest version [4.2.3](https://www.npmjs.com/package/cordova-plugin-document-scanner) and let me know if you are still running into problems. Closing this issue for now.

Thanks for your contribution !!! :))

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by cytostatic** [comment]
Hey @ChrisTomAlx 

works fine. Thanks for your fix.
It is a really nice plugin.

Cheers,
Cytostatic
