### ISSUE TITLE
Feature Request: ability to preselect a filter

### ISSUE THREAD

**Issue by dylanvdmerwe** [NeutrinosPlatform/cordova-plugin-document-scanner#7]
It would be good to be able to specify which filter (B&W, Enhanced, etc) is automatically selected.

Something like:
`scan.scanDoc(sourceType, filterIndex, scanSuccess, scanError);`

**Comment by ChrisTomAlx** [comment]
That is a pretty good idea. We have add this to our list of future enhancements.
