### ISSUE TITLE
Xcode validation - unsupported architectures x86_64, i386

### ISSUE THREAD

**Issue by fredfrag** [NeutrinosPlatform/cordova-plugin-document-scanner#70]
Hi

I have finished creating an App using appery.io in which i have used this cordova plugin.
The plugin works great in the app when testing using an IPA file.

I now need to upload to Apple App Connect Store and its failing on 2 frameworks used by this plugin
IRLDocumentScanner
TOCropViewController

These 2 frameworks support x86_64, i386, arm64 & armv7.

The problems is that Apple no longer allow x86_64, i386.

Can I get these frameworks without x86_64, i386 ?

thanks in advance

**Comment by ChrisTomAlx** [comment]
Hey those architectures are for the simulator. Try the solution in #18 to get around this issue

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
