### ISSUE TITLE
Ionic 5 & Anuglar 8 Project - error TS2749: 'DocumentScanner' refers to a value, but is being used as a type here.

### ISSUE THREAD

**Issue by andaniel2029** [NeutrinosPlatform/cordova-plugin-document-scanner#75]
**error TS2749: 'DocumentScanner' refers to a value, but is being used as a type here.**
I got above error when i installed plugin and used it on app.module.ts and other page.ts file.

help me, plz.

![image](https://user-images.githubusercontent.com/51064752/82114809-1eb95e80-9789-11ea-814b-be7074496811.png)

**Comment by ChrisTomAlx** [comment]
Hey @andaniel2029 

Apologies but you might have to ask the ionic guys about this. I don't have much to do with that integration. I am only involved in the pure cordova version of this plugin.  Sorry I could not be of more help..

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
