### ISSUE TITLE
Document Scan fails in Android

### ISSUE THREAD

**Issue by macsupport** [NeutrinosPlatform/cordova-plugin-document-scanner#76]
**Describe the bug**
Fails in Android after image taken with camera with 

**To Reproduce**
Click Scan, camera opens, image taken, returning to App shows error.

**Expected behavior**
Image should be saved

**Screenshots**
![Screenshot_1593463781](https://user-images.githubusercontent.com/624656/86054737-8660fb80-ba0f-11ea-9b8e-7716a09ac093.png)

**Smartphone (please complete the following information):**
 - Device: Nexus 6 P emulated
 - OS: Android 9 x86
 - Browser 
 - Version 28
 - Cordova Version 9.0.1
 - Cordova Platform Android
 - Cordova Platform Version 9.0.0

**Additional context**
Code to initiate Scan:

        function successCallback(imageData) {
	image = "data:image/jpeg;base64," + imageData; // Base64 rendering
	document.getElementById("myImage").src = image;

       alert(imageData);

       }

        function errorCallback(message) {
        alert('Failed because: ' + message);
     }

`scan.scanDoc(successCallback, errorCallback, {sourceType : 1, fileName : "Scanned_Image", quality : 1.0, returnBase64 : true}); `

**Comment by ChrisTomAlx** [comment]
Try with a real a device and see if the issue persists.

Cheers and Stay Safe :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by macsupport** [comment]
Thanks. Unfortunately, I don't have a real Android device for testing.

**Comment by ChrisTomAlx** [comment]
Closing this issue. Feel free to drop a message if you want to reopen it.

Cheers and Stay Safe :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
