### ISSUE TITLE
Remove the filter options (question)

### ISSUE THREAD

**Issue by SauloLauers1982** [NeutrinosPlatform/cordova-plugin-document-scanner#77]
Is there some way to remove the filter options, like B&W, grey and so. I whould like to force the user to have only the one I want to.

**Comment by ChrisTomAlx** [comment]
As of now no.
But if you are willing to take the time to raise a pr I could help. Closing this issue for now.

Cheers and have a nice day :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
