### ISSUE TITLE
Custom Folder for Images save

### ISSUE THREAD

**Issue by balvinder294** [NeutrinosPlatform/cordova-plugin-document-scanner#81]
Hi, first of all thanks for making this amazon plugin. I am using it along with Ionic  and works fine. Only thing i am looking for is how, to override the image storage path to a custom folder.
The purpose is to show the scanned images from that folder. Any idea help regarding this.
Thanks.

**Comment by ChrisTomAlx** [comment]
Hey @balvinder294 
If you just want to create a new folder you can use the response of the plugin and copy it into a new folder that you create. You might be able to use cordova-plugin-file to create a new folder and copy the scanned images (plugin response) there. There is a base64 return option if copying using URI does not work

Cheers and have a nice day :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by balvinder294** [comment]
Thanks for the help and idea, i was about to do something else. Also, so returning base64url will not save the file there in default folder ?

**Comment by ChrisTomAlx** [comment]
No it will still save. That is being done by the library part. So if you do it this way you will have 2 copies. If you would like you get your hands dirty and dive into the native code.  For android I would suggest looking at the [library code](https://github.com/NeutrinosPlatform/scanlibrary) and for ios just the [plugin code](https://github.com/NeutrinosPlatform/cordova-plugin-document-scanner/blob/master/src/ios/Scan.m).

Cheers and have a nice day :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by balvinder294** [comment]
Well thanks, i was going for this idea only. I will try to over ride paths in the plugin itself.
