### ISSUE TITLE
Scanning is not working on android 10

### ISSUE THREAD

**Issue by scramatte** [NeutrinosPlatform/cordova-plugin-document-scanner#86]
Hello,

When I run plugin with cordova 10  on Android 10 the plugin open  camera native view instead of embedded view in cordova app.  

I need to make a shot and so it come back to cordova app and show black screen with  folder button and camara button on bottom.  From now, If  I choose a photo from file it works. Camera still not working.

Scanning is not working.  Not that use Framework7 + vue  

**To Reproduce**
Just install cordova plugin
Make a button with click event handler with following code

 ```
scan.scanDoc((imgData) => {
          console.log(imageData)
          app.dialog.alert('done')
        }, (message) => {
          app.dialog.alert(message)
          console.err(message)
        }, {
          sourceType : 1,
          fileName : "myfile",
          quality : 2.5,
          returnBase64 : true
        });
```
**Expected behavior**
Get abiltity to scan documents

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OPPO A9 2020
 - OS:  Android 10  color OS 7.1
 - Browser: stock browser
 - Plugin Version:  tested with same result on 4.x.x and 5.0.0-beta 
 - Cordova Version: 10.0.0
 - Cordova Platform: android
 - Cordova Platform Version: 9.0.0

**Additional context**

**Comment by chandruBalamurugan1995** [comment]
i have same issue it will work on android 8.0.0 but we cannot use no more, cause playstore change target sdk version.

**Comment by ChrisTomAlx** [comment]
Is this a duplicate of #82 or #74? If so please close the issue and put your comments under the appropriate issue.

Cheers and have a nice day :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by scramatte** [comment]
Looks same problem as in #82.

**Comment by scramatte** [comment]
I was thinking that is a duplicate of #82 but finally looks different issue.
