### ISSUE TITLE
Demo application or template

### ISSUE THREAD

**Issue by lroal** [NeutrinosPlatform/cordova-plugin-document-scanner#88]
Hello, this seems like a very promising library.
Does there exist any reference implentation for cordova in github somewhere ?
Or a published app in google play/itunes just to test the features ?

**Comment by lroal** [comment]
Maybe combined with OCR https://github.com/NeutrinosPlatform/cordova-plugin-mobile-ocr..

**Comment by ChrisTomAlx** [comment]
Nothing made by us, But you are welcome to create one and I can add a backlink to the readme of these plugins.
Also both plugins have code snippets in the readme which you can directly copy paste onto a very basic project to get an understanding on how the plugins work.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
