### ISSUE TITLE
Incorrect result or user canceled the action

### ISSUE THREAD

**Issue by tiplonski** [NeutrinosPlatform/cordova-plugin-document-scanner#89]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Cordova Version [e.g. 8.0.0]
 - Cordova Platform [iOS]
 - Cordova Platform Version [4.5.5]

**Additional context**

Hello,

I have updated to the newest version of 4.6.2 and I am running the newest version of Android on my Samsung Galaxy Note 20.  I have also upgraded to the newest CLI of Ionic. The problem is I am getting the following error when pressing "OK" after taking a picture:

Incorrect result or user canceled the action

Please let me know if anyone else has had the same or similar error.

**Comment by ChrisTomAlx** [comment]
Could you try the beta version and see if that solves the issue. You can look at this [comment ](https://github.com/NeutrinosPlatform/cordova-plugin-document-scanner/issues/74#issuecomment-724667450) to get an idea how to do this

Cheers and have a nice day :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by tiplonski** [comment]
Hello Chris,

That looked to resolve the issue.  Thanks!

-Tim

**Comment by ciclick** [comment]
Hello Chris, I've just updated to the beta version but now Android Studio returns this errors:

> Task :app:processDebugManifest FAILED
/Users/toniarrebola/projectesGIT/bacs_app/android/app/src/main/AndroidManifest.xml:36:13-64 Error:
	Attribute provider#androidx.core.content.FileProvider@authorities value=(io.ionic.starter.fileprovider) from AndroidManifest.xml:36:13-64
	is also present at [com.github.NeutrinosPlatform:scanlibrary:3.2] AndroidManifest.xml:32:13-76 value=(io.ionic.starter.com.scanlibrary.provider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:34:9-42:20 to override.
/Users/toniarrebola/projectesGIT/bacs_app/android/app/src/main/AndroidManifest.xml:41:17-51 Error:
	Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/file_paths) from AndroidManifest.xml:41:17-51
	is also present at [com.github.NeutrinosPlatform:scanlibrary:3.2] AndroidManifest.xml:37:17-55 value=(@xml/provider_paths).
	Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml:39:13-41:64 to override.

I use capacitor

Thank you

**Comment by SauloLauers** [comment]
I still have that same problem. It seems to happen on android 10 and bellow. I tried with may android versions, at android 11 it works. 

`    openScanner() {
        LoadingUtil.showLoading(this.loadingCtrl);
        let opts: DocumentScannerOptions = {};

        this.documentScanner.scanDoc(opts)
            .then((fileUri: string) => {
                console.log('documentScanner.scanDoc');
                console.log(fileUri);
                if (this.platform.is('android')) {
                    this.getAndroidRealPath(fileUri).subscribe(realPath => {
                        this.enviaArquivoDigital(fileUri, this.getExtensaoArquivo(realPath));
                    });
                } else {
                    fileUri = fileUri.indexOf('file://') == 0 ? fileUri : 'file://' + fileUri;
                    this.enviaArquivoDigital(fileUri, this.getExtensaoArquivo(fileUri));
                }
                LoadingUtil.dismiss();
            })
            .catch((error: any) => {
                LoadingUtil.dismiss();
                console.log('erro ao anexar arquivo da camera');
                console.log(error)
            });
    }`

It used to work. But now we had to increase the mininum API lvl, and it started.

**Comment by sergiuturus** [comment]
Any updates on this? I get the same error + android studio error @ciclick described
