### ISSUE TITLE
iOS and Android permissions

### ISSUE THREAD

**Issue by dylanvdmerwe** [NeutrinosPlatform/cordova-plugin-document-scanner#9]
Permissions need to be properly setup (or asked from the user). 

Should be setup in the config.xml file of the plugin. 

For example on iOS 10+ the app crashes as permissions have not been set by the plugin:
```
2018-05-08 14:07:09.272948+0200 Antel[320:10357] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.
```

Android also needs to prompt for permissions properly.

Example:
![image](https://user-images.githubusercontent.com/2852839/39756363-8f57b562-52c9-11e8-8dba-8feccf346c5c.png)

**Comment by ChrisTomAlx** [comment]
> The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

This has actually already been done. Our tests did not yield this error. Anyhow will check again as soon as possible.
Android does ask for camera permission the first time camera is opened. Was this not the case in your tests?
