### ISSUE TITLE
Ionic Capacitor - iOS build problem - 'IRLScannerViewController.h' file not found

### ISSUE THREAD

**Issue by suvarnak** [NeutrinosPlatform/cordova-plugin-document-scanner#91]
**Describe the bug**
I have an an ionic app project with capacitor. I have added document scanner plugin using these 2 packages -  cordova-plugin-document-scanner and @ionic-native/document-scanner. I could build the android version and its working fine. However when I tried to build iOS app using xcode I am getting following error - 

/users/suvarna/development/reportapp/ios/capacitor-cordova-ios-plugins/sources/CordovaPluginDocumentScanner/src/ios/IRLDocumentScanner.framework/PrivateHeaders/IRLCameraView.h:14:9: error: 'IRLScannerViewController.h' file not found
#import "IRLScannerViewController.h"

**Build Environment:**
 - Device: Macbook Air M1 (Also getting same error on intel mac)
 - OS: MacOS 11.0
 - XCode: 12.3
 - Plugin Version: 4.2.6 and 5.0.0-beta.0
 - Capacitor version:  2.4.1

**Comment by rampellisrinu** [comment]
Hi @suvarnak,

were you able to solve this issue? am also facing same problem with document scanner. This plugin not working for iOS.

Please share thoughts how to resolve this issue.

**Comment by lzoubek** [comment]
Hi @suvarnak I also cannot build plugin for ios having same error, same versions, except XCode .. I run 12.5.1
