### ISSUE TITLE
big apk file and  Compatible side by side NDK warning 

### ISSUE THREAD

**Issue by brunoalex** [NeutrinosPlatform/cordova-plugin-document-scanner#92]
apk file is 40mb due to this libs on cordova 9.0.0:

WARNING: Compatible side by side NDK version was not found. Default is 21.0.6113669.
Compatible side by side NDK version was not found. Default is 21.0.6113669.
Unable to strip the following libraries, packaging them as they are: libScanner.so, libopencv_java3.so.

**Comment by ChrisTomAlx** [comment]
Refer to #45 to reduce apk size. I am not sure about the NDK warning though.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
