### ISSUE TITLE
Defaulting to B&W Scan

### ISSUE THREAD

**Issue by robendorf** [NeutrinosPlatform/cordova-plugin-document-scanner#94]
Is there a way to remove icons or to create a default setting to B&W?

![2021-03-09_17-21-34](https://user-images.githubusercontent.com/38294458/110561506-a3041600-80fc-11eb-8c12-b1c29d5ab2fe.jpg)

Thanks

**Comment by ChrisTomAlx** [comment]
Duplicate #60 

[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
