### ISSUE TITLE
Not able to take(scan) photo using camera

### ISSUE THREAD

**Issue by ragul02** [NeutrinosPlatform/cordova-plugin-document-scanner#95]
When I'm trying to take the photo to scan the doc, getting an error as  '**incorrect result or user cancelled the action**'.

Dependencies:
    "cordova-plugin-document-scanner": "^5.0.0-beta.1"

Tested in Android 10 version.

**Comment by ChrisTomAlx** [comment]
Are you getting any error logs in Android Studio? 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ragul02** [comment]
I didn't debug it. I checked in mobile device.

**Comment by ChrisTomAlx** [comment]
I am not a magician @ragul02 .. :)) .. Please share error logs if you are expecting help here.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
